export type Unit19DocumentStatus =
  | "available"
  | "watchlist"
  | "trace_only"
  | "pending"
  | "missing"
  | "deferred"
  | "weak_evidence";

export type Unit19DocumentPriority = "critical" | "high" | "medium" | "low";

export type Unit19DocumentCategory = {
  id: string;
  name: string;
  description: string;
};

export type Unit19DocumentRecord = {
  id: string;
  order: number;
  title: string;
  categoryId: string;
  status: Unit19DocumentStatus;
  priority: Unit19DocumentPriority;
  fileName?: string;
  source?: string;
  proves: string;
  controlNote?: string;
  nextAction?: string;
  date?: string;
  amountEur?: number;
  tags?: string[];
};

export const unit19DocumentCategories: Unit19DocumentCategory[] = [
  {
    id: "deal-payments",
    name: "Deal & Payments",
    description: "Agreements, deposits, final payments, brokerage and payment traces.",
  },
  {
    id: "ownership-notary",
    name: "Ownership & Notary",
    description: "Notarial deed, cancellation-condition removal, notary folder and closing evidence.",
  },
  {
    id: "tax-aade",
    name: "Tax & AADE",
    description: "FMA, myPROPERTY, FYAA, E9 and Greek tax receipts.",
  },
  {
    id: "cadastre",
    name: "Cadastre",
    description: "Ktimatologio descriptive/spatial extracts, certificates and post-removal status.",
  },
  {
    id: "technical-legalization",
    name: "Technical / Legalization",
    description: "Building Identity, N.4495, PEA, plans and legalized-area evidence.",
  },
  {
    id: "lease-tenant",
    name: "Lease & Tenant",
    description: "Old and new lease layer, tenant deposit, AADE rental declaration and acceptance.",
  },
  {
    id: "utilities-operations",
    name: "Utilities & Operations",
    description: "Water, electricity, gas, building fees and operational handover evidence.",
  },
  {
    id: "fees-receipts",
    name: "Fees / Receipts / Weak Evidence",
    description: "Administrative payments, intermediary payments, internal traces and weaker proof items.",
  },
];

export const unit19DocumentsSeed: Unit19DocumentRecord[] = [
  {
    id: "preliminary-agreement",
    order: 1,
    title: "Preliminary agreement",
    categoryId: "deal-payments",
    status: "available",
    priority: "high",
    fileName: "ΙΔΙΩΤΙΚΟ ΣΥΜΦΩΝΗΤΙΚΟ Signed, Translated.pdf",
    proves:
      "Transaction frame for €90,000, initial €5,000 deposit, €85,000 balance and lease until 30.09.2026 at €450 according to the agreement text.",
    amountEur: 90000,
    tags: ["agreement", "deposit", "lease"],
  },
  {
    id: "initial-deposit-trace",
    order: 2,
    title: "Initial deposit to sellers",
    categoryId: "deal-payments",
    status: "trace_only",
    priority: "medium",
    source: "Described inside notarial deed",
    proves:
      "The notarial deed confirms €2,500 paid to Athina Vatou and €2,500 paid to Anastasia Vatou on 04.03.2026.",
    amountEur: 5000,
    date: "2026-03-04",
    controlNote: "No separate bank file currently kept; the deed preserves the payment trace.",
    tags: ["deposit", "trace"],
  },
  {
    id: "second-payment-trace",
    order: 3,
    title: "Second payment to sellers",
    categoryId: "deal-payments",
    status: "trace_only",
    priority: "medium",
    source: "Described inside notarial deed",
    proves:
      "The notarial deed confirms €7,500 paid to Athina Vatou and €7,500 paid to Anastasia Vatou on 07.04.2026.",
    amountEur: 15000,
    date: "2026-04-07",
    controlNote: "No separate bank file currently kept; the deed preserves the payment trace.",
    tags: ["payment", "trace"],
  },
  {
    id: "signed-notarial-deed-9555",
    order: 4,
    title: "Signed notarial deed №9555",
    categoryId: "ownership-notary",
    status: "watchlist",
    priority: "critical",
    fileName: "Notarial Deed Dimosthenous Mitropoulou №14 Signed.pdf",
    proves:
      "Purchase-sale for €90,000, objective value €31,594.68 and deed under cancellation condition until full payment.",
    controlNote:
      "Available, but it still requires documentary closure through πράξη εξόφλησης και άρσης της διαλυτικής αίρεσης and cadastre registration of that removal.",
    nextAction: "Obtain the removal act and proof of its registration in Ktimatologio.",
    amountEur: 90000,
    tags: ["deed", "ownership", "cancellation condition", "άρση"],
  },
  {
    id: "notarial-deed-copy",
    order: 5,
    title: "Scanned / unsigned deed copy",
    categoryId: "ownership-notary",
    status: "available",
    priority: "low",
    fileName: "Notarial Deed Dimosthenous Mitropoulou №14.pdf",
    proves: "Reserve scan / visual copy of the same deed.",
    tags: ["deed", "backup"],
  },
  {
    id: "final-payment-anastasia",
    order: 6,
    title: "Final payment to Anastasia Vatou",
    categoryId: "deal-payments",
    status: "available",
    priority: "critical",
    fileName: "Final Payment Anastasia Vatou 35000 EUR 29.04.2026.pdf",
    proves:
      "SEPA transfer of €35,000 dated 29.04.2026; reason: final payment, KAEK 190445711002/0/3, notarial deed 9555.",
    date: "2026-04-29",
    amountEur: 35000,
    tags: ["SEPA", "final payment", "KAEK"],
  },
  {
    id: "final-payment-athina",
    order: 7,
    title: "Final payment to Athina Vatou",
    categoryId: "deal-payments",
    status: "available",
    priority: "critical",
    fileName: "Final Payment Athina Vatou 35000 EUR 29.04.2026.pdf",
    proves:
      "SEPA transfer of €35,000 dated 29.04.2026; reason: final payment, KAEK 190445711002/0/3, notarial deed 9555.",
    date: "2026-04-29",
    amountEur: 35000,
    tags: ["SEPA", "final payment", "KAEK"],
  },
  {
    id: "fma-payment-slip",
    order: 8,
    title: "Transfer tax / FMA payment slip",
    categoryId: "tax-aade",
    status: "available",
    priority: "high",
    fileName: "Данък придобиване 2781 Евро 01.04.2026.pdf",
    proves: "Paid €2,781 FMA on 01.04.2026, AFM 203131282.",
    date: "2026-04-01",
    amountEur: 2781,
    tags: ["FMA", "ΦΜΑ", "tax"],
  },
  {
    id: "fma-aade-receipt",
    order: 9,
    title: "Transfer tax / FMA AADE receipt",
    categoryId: "tax-aade",
    status: "available",
    priority: "high",
    fileName: "Разписка Данък придобиване 2781 Евро 01.04.2026.htm",
    proves: "Successful payment of €2,781 obligation, payment code 000578545665.",
    date: "2026-04-01",
    amountEur: 2781,
    tags: ["AADE", "receipt", "FMA"],
  },
  {
    id: "myproperty-fma-declaration",
    order: 10,
    title: "myPROPERTY / FMA declaration",
    categoryId: "tax-aade",
    status: "trace_only",
    priority: "high",
    source: "myPROPERTY text + FYAA files",
    proves:
      "Declaration 31308/2026, registration 2878311, completed, tax base €90,000, tax €2,781.",
    controlNote: "If a PDF export exists, keep it as the stronger archive file.",
    nextAction: "Add PDF export if available.",
    tags: ["myPROPERTY", "FMA", "FYAA"],
  },
  {
    id: "fyaa-apartment",
    order: 11,
    title: "FYAA valuation sheet for apartment",
    categoryId: "tax-aade",
    status: "available",
    priority: "medium",
    fileName: "FYAA1_2878311 (2).pdf",
    proves: "Objective apartment value €26,212.68; area 37.34 sqm.",
    amountEur: 26212.68,
    tags: ["FYAA", "objective value", "area"],
  },
  {
    id: "fyaa-storage",
    order: 12,
    title: "FYAA valuation sheet for storage",
    categoryId: "tax-aade",
    status: "available",
    priority: "medium",
    fileName: "FYAA1_2878311 (3).pdf",
    proves: "Objective storage value €5,382; area 6 sqm.",
    amountEur: 5382,
    tags: ["FYAA", "storage"],
  },
  {
    id: "e9-declared-property",
    order: 13,
    title: "E9 / declared property status",
    categoryId: "tax-aade",
    status: "watchlist",
    priority: "high",
    fileName: "Certificate of Declared Property Status (E9).pdf",
    proves:
      "E9 as of 01.01.2027 declares 37.34 sqm main areas + 6.00 sqm auxiliary areas, KAEK 190445711002/0/3, 100% ownership.",
    controlNote:
      "Area mismatch remains deferred. Return to it before future sale, refinance, new loan or major legal/banking procedure.",
    nextAction: "Keep deferred compliance note active; do not open this front before priority items close.",
    tags: ["E9", "area", "deferred"],
  },
  {
    id: "pea-energy-certificate",
    order: 14,
    title: "PEA / Energy Performance Certificate",
    categoryId: "technical-legalization",
    status: "available",
    priority: "medium",
    fileName: "Energy Performance Certificate.pdf",
    proves: "PEA №32586/2024, code M5HAU-D7X4N-1PEPJ-O, area 37.34 sqm.",
    tags: ["PEA", "energy certificate"],
  },
  {
    id: "building-identity",
    order: 15,
    title: "Building Identity / Technical Passport",
    categoryId: "technical-legalization",
    status: "watchlist",
    priority: "high",
    fileName: "Building Identity Certificate (Technical Passport).pdf",
    proves:
      "Certificate of completeness for building / divided property identity, KAEK 190445711002/0/3.",
    controlNote:
      "Technical package explains the area history, but the E9 / full-area correction is not being solved now.",
    tags: ["Building Identity", "TEE", "KAEK"],
  },
  {
    id: "n4495-package",
    order: 16,
    title: "N.4495 technical package",
    categoryId: "technical-legalization",
    status: "watchlist",
    priority: "high",
    fileName: "N. 4495.pdf",
    proves: "Additional technical / legalization / identity package.",
    controlNote:
      "Relevant for legalized-area history. Keep connected to the deferred E9/full-area issue.",
    tags: ["N.4495", "legalization", "area"],
  },
  {
    id: "existing-lease",
    order: 17,
    title: "Existing lease contract",
    categoryId: "lease-tenant",
    status: "available",
    priority: "high",
    fileName: "Existing Lease Contract.pdf",
    proves:
      "Lease dated 09.09.2024, tenant Nikoleta Kalampoka, rent €450, term 15.09.2024–14.09.2026, deposit €450, with 37.34 sqm + adjacent room around 15 sqm described.",
    amountEur: 450,
    tags: ["lease", "tenant", "Nikoleta"],
  },
  {
    id: "security-deposit-receipt",
    order: 18,
    title: "Tenant security deposit receipt",
    categoryId: "lease-tenant",
    status: "available",
    priority: "medium",
    fileName: "Security Deposit Receipt 450 Euro.pdf",
    proves: "Handwritten receipt for €450 deposit connected with the lease relationship.",
    amountEur: 450,
    tags: ["deposit", "tenant"],
  },
  {
    id: "aade-rental-declaration",
    order: 19,
    title: "AADE rental declaration",
    categoryId: "lease-tenant",
    status: "watchlist",
    priority: "critical",
    fileName: "AADE Rental Declaration Receipt 115905002 - Unit 19 - 11.05.2026.pdf",
    proves:
      "Declaration №115905002 filed on 11.05.2026; landlord BRAMBASHKI ILKO 100%, tenant KALAMPOKA NIKOLETA, rent €450, term 16.04.2026–14.09.2026.",
    controlNote:
      "The declaration says no energy certificate was defined although PEA exists. Tenant acceptance also needs confirmation.",
    nextAction: "Confirm tenant acceptance and whether a corrective declaration with PEA is required.",
    date: "2026-05-11",
    amountEur: 450,
    tags: ["AADE", "rental", "PEA", "tenant acceptance"],
  },
  {
    id: "water-registration",
    order: 20,
    title: "Water account registration / EYATH",
    categoryId: "utilities-operations",
    status: "watchlist",
    priority: "medium",
    fileName: "Water Account Registration.pdf",
    proves: "EYATH profile for address Mitropoulou Dimitri 14, with contact details.",
    controlNote: "Useful trace, but a real bill or active-account confirmation is still preferable.",
    nextAction: "Add current bill or active account confirmation when available.",
    tags: ["EYATH", "water"],
  },
  {
    id: "cadastre-registration-extract",
    order: 21,
    title: "Cadastre descriptive extract",
    categoryId: "cadastre",
    status: "watchlist",
    priority: "critical",
    fileName: "Cadastre Registration - KAEK 190445711002-0-3 - 11.05.2026.pdf",
    proves:
      "Descriptive base extract, KAEK 190445711002/0/3, showing history and Ilko as acquirer 100/100, but with cancellation-condition note.",
    controlNote:
      "Not final. As of 11.05.2026 it still contains ΥΠΟ ΔΙΑΛΥΤΙΚΗ ΑΙΡΕΣΗ / ΠΡΟΘΕΣΜΙΑ.",
    nextAction: "Obtain updated descriptive extract after cancellation-condition removal.",
    date: "2026-05-11",
    tags: ["KAEK", "cadastre", "άρση"],
  },
  {
    id: "cadastre-spatial-extract",
    order: 22,
    title: "Cadastre spatial extract",
    categoryId: "cadastre",
    status: "available",
    priority: "medium",
    fileName: "Cadastre Spatial Extract - KAEK 190445711002-0-3 - Unit 19 - 11.05.2026.pdf",
    proves:
      "Spatial base extract, KAEK 190445711002/0/3, geotemachio 236 sqm; explicitly not a certificate of legal use.",
    date: "2026-05-11",
    tags: ["cadastre", "spatial", "KAEK"],
  },
  {
    id: "notary-fees-initial-registration",
    order: 23,
    title: "Notary fees and initial registration",
    categoryId: "fees-receipts",
    status: "available",
    priority: "medium",
    fileName: "Нот. такси и първоначално вписване 1140 Евро 01.04.2026.pdf",
    proves: "Transfer of €1,140 to Radostina Grampas for notary fees / initial registration / Thessaloniki apartment.",
    date: "2026-04-01",
    amountEur: 1140,
    tags: ["fees", "notary", "registration"],
  },
  {
    id: "cadastre-notary-fees-700",
    order: 24,
    title: "Cadastre / notary fees 680/700",
    categoryId: "fees-receipts",
    status: "watchlist",
    priority: "medium",
    fileName: "Такси 680 евро (реално платени на Р. Грампас за нотариуса).pdf",
    proves: "Transfer of €700 to Radostina Grampas for cadastre registration / Thessaloniki apartment.",
    controlNote: "Keep as actually paid €700; expected/discussed amount was €680.",
    amountEur: 700,
    tags: ["fees", "cadastre", "Radostina"],
  },
  {
    id: "cash-fees-580",
    order: 25,
    title: "Cash fees €580",
    categoryId: "fees-receipts",
    status: "weak_evidence",
    priority: "low",
    fileName: "Такси 580 евро в брой.txt",
    proves: "Internal text note: given to Radostina Grampas for the notary.",
    controlNote: "Available as internal trace only; weak evidence without receipt/invoice/breakdown.",
    amountEur: 580,
    tags: ["cash", "weak evidence", "fees"],
  },
  {
    id: "e9-state-fee",
    order: 26,
    title: "E9 state fee",
    categoryId: "fees-receipts",
    status: "available",
    priority: "medium",
    fileName: "Държавна такса Е9 254 Евро 15.04.2026.pdf",
    proves: "Transfer of €254 to Radostina Grampas; reason: E9 state fee for Thessaloniki apartment.",
    date: "2026-04-15",
    amountEur: 254,
    tags: ["E9", "fee"],
  },
  {
    id: "lease-registration-fee",
    order: 27,
    title: "Lease registration fee",
    categoryId: "fees-receipts",
    status: "available",
    priority: "medium",
    fileName: "Регистрация договор за наем 350 Euro 29.04.2026.pdf",
    proves: "Transfer of €350 to Radostina Grampas; reason: lease registration for Thessaloniki apartment.",
    date: "2026-04-29",
    amountEur: 350,
    tags: ["lease", "fee"],
  },
  {
    id: "broker-commission",
    order: 28,
    title: "Broker commission",
    categoryId: "deal-payments",
    status: "available",
    priority: "medium",
    fileName: "Broker Commission Receipt 1800 Euro.pdf",
    proves: "Handwritten receipt for €1,800 property sale brokerage.",
    amountEur: 1800,
    tags: ["broker", "commission"],
  },
  {
    id: "removal-act",
    order: 29,
    title: "Πράξη εξόφλησης και άρσης της διαλυτικής αίρεσης",
    categoryId: "ownership-notary",
    status: "pending",
    priority: "critical",
    source: "Notary / lawyer",
    proves:
      "The deed states that after payment of €70,000 the sellers must sign an act confirming payment and removing the cancellation condition.",
    nextAction: "Request signed act from notary / lawyer; confirm whether sellers signed directly or via authorization.",
    tags: ["άρση", "cancellation condition", "notary"],
  },
  {
    id: "removal-act-cadastre-registration",
    order: 30,
    title: "Proof of cadastre registration of the removal act",
    categoryId: "cadastre",
    status: "pending",
    priority: "critical",
    source: "Notary / Ktimatologio",
    proves:
      "The payment proves money was sent; cadastre registration proves the condition was removed from the property record.",
    nextAction: "Obtain proof that the removal act was registered in Ktimatologio.",
    tags: ["cadastre", "άρση", "critical"],
  },
  {
    id: "updated-cadastre-after-removal",
    order: 31,
    title: "Updated descriptive cadastre extract after removal",
    categoryId: "cadastre",
    status: "pending",
    priority: "critical",
    source: "Ktimatologio / notary",
    proves:
      "A new extract should show no active ΥΠΟ ΔΙΑΛΥΤΙΚΗ ΑΙΡΕΣΗ / ΠΡΟΘΕΣΜΙΑ note.",
    nextAction: "Request updated descriptive extract after άρση registration.",
    tags: ["cadastre", "KAEK", "critical"],
  },
  {
    id: "official-cadastre-certificate",
    order: 32,
    title: "Official cadastre certificate if required",
    categoryId: "cadastre",
    status: "pending",
    priority: "medium",
    source: "Ktimatologio",
    proves: "Official certificate if needed beyond the available extracts.",
    nextAction: "Clarify with notary/lawyer if an official certificate is necessary for final archive.",
    tags: ["cadastre", "certificate"],
  },
  {
    id: "tenant-acceptance-status",
    order: 33,
    title: "AADE lease acceptance by Nikoleta",
    categoryId: "lease-tenant",
    status: "pending",
    priority: "critical",
    source: "AADE / lawyer / tenant",
    proves: "Confirms whether the rental declaration has been accepted by the tenant.",
    nextAction: "Ask for accepted status / screenshot / confirmation.",
    tags: ["AADE", "tenant acceptance", "lease"],
  },
  {
    id: "pea-rental-declaration-correction",
    order: 34,
    title: "PEA correction or opinion for AADE rental declaration",
    categoryId: "lease-tenant",
    status: "pending",
    priority: "critical",
    source: "Lawyer / AADE",
    proves: "Clarifies whether the rental declaration must be corrected because PEA was not defined.",
    nextAction: "Ask lawyer/AADE whether corrective declaration with PEA is required.",
    tags: ["PEA", "AADE", "correction"],
  },
  {
    id: "floor-plans",
    order: 35,
    title: "Full floor plans / κατόψεις",
    categoryId: "technical-legalization",
    status: "pending",
    priority: "high",
    source: "Notary / engineer",
    proves:
      "The deed says ground-floor and roof-level plans are attached and correspond to TEE/N.4495 platform.",
    nextAction: "Collect separate plan files if they are not already included in the Building Identity package.",
    tags: ["plans", "κατόψεις", "TEE"],
  },
  {
    id: "final-notary-folder",
    order: 36,
    title: "Final notary folder with deed attachments",
    categoryId: "ownership-notary",
    status: "pending",
    priority: "high",
    source: "Notary",
    proves:
      "The deed lists attachments such as tax clearance, insurance clearance, ENFIA certificates, cadastre extract, PEA and Building Identity.",
    nextAction: "Request final folder / file package from notary.",
    tags: ["notary folder", "attachments"],
  },
  {
    id: "electricity-account-proof",
    order: 37,
    title: "Electricity account / holder proof",
    categoryId: "utilities-operations",
    status: "pending",
    priority: "medium",
    source: "Electricity provider / tenant / lawyer",
    proves:
      "E9 and AADE lease include meter/account number 221552209, but there is no separate electricity document yet.",
    nextAction: "Collect profile, bill or holder confirmation.",
    tags: ["electricity", "utilities"],
  },
  {
    id: "gas-account-proof",
    order: 38,
    title: "Gas account / holder proof",
    categoryId: "utilities-operations",
    status: "pending",
    priority: "medium",
    source: "Gas provider / tenant / lawyer",
    proves: "Clarifies active gas account and holder if gas is active.",
    nextAction: "Collect profile, bill or holder confirmation.",
    tags: ["gas", "utilities"],
  },
  {
    id: "water-current-bill",
    order: 39,
    title: "Water active account / current bill",
    categoryId: "utilities-operations",
    status: "pending",
    priority: "medium",
    source: "EYATH",
    proves: "Confirms real account transfer / active current water account, beyond profile registration.",
    nextAction: "Add current bill or active transfer confirmation.",
    tags: ["water", "EYATH"],
  },
  {
    id: "fee-breakdown-radostina-notary",
    order: 40,
    title: "Invoice / breakdown for Radostina / notary fees",
    categoryId: "fees-receipts",
    status: "pending",
    priority: "medium",
    source: "Lawyer / Radostina / notary",
    proves: "Useful for financial control and archive clarity, less critical for ownership proof.",
    nextAction: "Request breakdown if possible without creating unnecessary friction.",
    tags: ["fees", "invoice", "breakdown"],
  },
  {
    id: "digital-transfer-folder-final-status",
    order: 41,
    title: "Final status from Digital Transfer Folder",
    categoryId: "ownership-notary",
    status: "pending",
    priority: "high",
    source: "Notary / akinita.gov.gr",
    proves: "Screenshot, extract or final folder status confirming the transaction folder is completed.",
    nextAction: "Ask for final status evidence if lawyer says the transaction folder is completed.",
    tags: ["Digital Transfer Folder", "notary", "completion"],
  },
];
