export type Unit19ExpenseStatus = "paid" | "clarify" | "excluded";

export type Unit19ExpenseCategory =
    | "Bulgarian documents"
    | "Greek setup & legal"
    | "Credit / DSK"
    | "Greek closing"
    | "Post-acquisition"
    | "Vehicle / excluded";

export type Unit19Expense = {
    id: string;
    sourceRow: number;
    title: string;
    category: Unit19ExpenseCategory;
    bgn: number;
    eur: number;
    issuer: string;
    note: string;
    status: Unit19ExpenseStatus;
};

export const EUR_TO_BGN = 1.95583;

function fromBgn(value: number) {
    return Number((value / EUR_TO_BGN).toFixed(2));
}

function fromEur(value: number) {
    return Number((value * EUR_TO_BGN).toFixed(2));
}

export const unit19Expenses: Unit19Expense[] = [
    {
        id: "doc-004",
        sourceRow: 4,
        title: "Пълномощно от Здравка Бръмбашка",
        category: "Bulgarian documents",
        bgn: 45,
        eur: fromBgn(45),
        issuer: "Нотариус до съда, Бяла Слатина",
        note: "Упълномощава Илко Бръмбашки, безсрочно, пред Асет банк и поземлена комисия, непълно.",
        status: "paid",
    },
    {
        id: "doc-005",
        sourceRow: 5,
        title: "Удостоверение за наследници",
        category: "Bulgarian documents",
        bgn: 8.91,
        eur: fromBgn(8.91),
        issuer: "Община Бяла Слатина",
        note: "Здравка Бръмбашка и Илко Бръмбашки",
        status: "paid",
    },
    {
        id: "doc-009",
        sourceRow: 9,
        title: "Скица на поземлен имот къща, Цв. Бръмбашки",
        category: "Bulgarian documents",
        bgn: 40.91,
        eur: fromBgn(40.91),
        issuer: "Община Бяла Слатина",
        note: "Изд. на 26.11.2025 г.",
        status: "paid",
    },
    {
        id: "doc-010",
        sourceRow: 10,
        title: "Данъчна оценка къща, Цв. Бръмбашки",
        category: "Bulgarian documents",
        bgn: 20,
        eur: fromBgn(20),
        issuer: "Община Бяла Слатина",
        note: "Валидна до 31.12.2025 г.",
        status: "paid",
    },
    {
        id: "doc-011",
        sourceRow: 11,
        title: "Нотариален акт констативен",
        category: "Bulgarian documents",
        bgn: 840,
        eur: fromBgn(840),
        issuer: "Нотариус Геновева Христова, Бяла Слатина",
        note: "Собственици Здравка Бръмбашка и Илко Бръмбашки",
        status: "paid",
    },
    {
        id: "doc-012",
        sourceRow: 12,
        title: "Пазарна оценка къща",
        category: "Bulgarian documents",
        bgn: 320,
        eur: fromBgn(320),
        issuer: "Британ ООД, Плевен",
        note: "Независим оценител за ОББ",
        status: "paid",
    },
    {
        id: "doc-013",
        sourceRow: 13,
        title: "Заявление за изменение на данните в кадастъра",
        category: "Bulgarian documents",
        bgn: fromEur(42.96),
        eur: 42.96,
        issuer: "Община Бяла Слатина",
        note: "",
        status: "paid",
    },
    {
        id: "doc-014",
        sourceRow: 14,
        title: "Нова скица на поземлен имот по акт от 2025",
        category: "Bulgarian documents",
        bgn: fromEur(18.42),
        eur: 18.42,
        issuer: "Община Бяла Слатина",
        note: "",
        status: "paid",
    },
    {
        id: "doc-015",
        sourceRow: 15,
        title: "Нова данъчна оценка по акт от 2025",
        category: "Bulgarian documents",
        bgn: fromEur(15.34),
        eur: 15.34,
        issuer: "Община Бяла Слатина",
        note: "",
        status: "paid",
    },
    {
        id: "doc-016",
        sourceRow: 16,
        title: "Копие от кадастър 1971 г. и 1995 г.",
        category: "Bulgarian documents",
        bgn: fromEur(2.56),
        eur: 2.56,
        issuer: "Община Бяла Слатина",
        note: "",
        status: "paid",
    },
    {
        id: "doc-017",
        sourceRow: 17,
        title: "Удостоверение за тежести",
        category: "Bulgarian documents",
        bgn: fromEur(15.33),
        eur: 15.33,
        issuer: "Районен съд гр. Бяла Слатина",
        note: "",
        status: "paid",
    },
    {
        id: "doc-018",
        sourceRow: 18,
        title: "Declaration for Greek AFM Ilko Brambashki",
        category: "Greek setup & legal",
        bgn: fromEur(10),
        eur: 10,
        issuer: "Посолство на Гърция",
        note: "",
        status: "paid",
    },
    {
        id: "doc-019",
        sourceRow: 19,
        title: "Greek AFM Ilko Brambashki",
        category: "Greek setup & legal",
        bgn: fromEur(150),
        eur: 150,
        issuer: "ААДЕ",
        note: "Платени на Радостина Грампас",
        status: "paid",
    },
    {
        id: "doc-020",
        sourceRow: 20,
        title: "Обстоятелствена проверка на Unit 19",
        category: "Greek setup & legal",
        bgn: fromEur(540),
        eur: 540,
        issuer: "Радостина Грампас",
        note: "Unit 19",
        status: "paid",
    },
    {
        id: "doc-021",
        sourceRow: 21,
        title: "Техн. характеристика и скици земя Търнава",
        category: "Credit / DSK",
        bgn: fromEur(51.16),
        eur: 51.16,
        issuer: "Поземлена комисия, Бяла Слатина",
        note: "",
        status: "paid",
    },
    {
        id: "doc-023",
        sourceRow: 23,
        title: "Пълномощно от Здравка Бръмбашка",
        category: "Credit / DSK",
        bgn: fromEur(20),
        eur: 20,
        issuer: "Нотариус А. Карабенчева, Бяла Слатина",
        note: "За ДСК",
        status: "paid",
    },
    {
        id: "doc-024",
        sourceRow: 24,
        title: "Декларации от Здравка Бръмбашка",
        category: "Credit / DSK",
        bgn: fromEur(40),
        eur: 40,
        issuer: "Нотариус А. Карабенчева, Бяла Слатина",
        note: "За ДСК. По 25 от ЗННД, 42 от ЗМИП, 74 и 264 от ДОПК",
        status: "paid",
    },
    {
        id: "doc-025",
        sourceRow: 25,
        title: "Превод на предварителен договор Unit 19",
        category: "Credit / DSK",
        bgn: fromEur(70),
        eur: 70,
        issuer: "Бела Вентис ООД, Люлин",
        note: "Unit 19, превод за ДСК",
        status: "paid",
    },
    {
        id: "doc-028",
        sourceRow: 28,
        title: "Удостоверение за семейно положение",
        category: "Credit / DSK",
        bgn: fromEur(6),
        eur: 6,
        issuer: "Община Бяла Слатина",
        note: "За ДСК",
        status: "paid",
    },
    {
        id: "doc-029",
        sourceRow: 29,
        title: "Справка вписани завещания Цветан Бръмбашки",
        category: "Credit / DSK",
        bgn: fromEur(3),
        eur: 3,
        issuer: "Агенция по вписванията",
        note: "За ДСК",
        status: "paid",
    },
    {
        id: "doc-030",
        sourceRow: 30,
        title: "Такса за анализ на кредит",
        category: "Credit / DSK",
        bgn: fromEur(205),
        eur: 205,
        issuer: "ДСК",
        note: "",
        status: "paid",
    },
    {
        id: "doc-038",
        sourceRow: 38,
        title: "Нотариус кредит",
        category: "Credit / DSK",
        bgn: fromEur(675),
        eur: 675,
        issuer: "Нотариус А. Карабенчева, Бяла Слатина",
        note: "За ДСК",
        status: "paid",
    },
    {
        id: "doc-039",
        sourceRow: 39,
        title: "Удостоверение за тежести",
        category: "Credit / DSK",
        bgn: fromEur(15.33),
        eur: 15.33,
        issuer: "Районен съд гр. Бяла Слатина",
        note: "За ДСК",
        status: "paid",
    },
    {
        id: "doc-041",
        sourceRow: 41,
        title: "Застраховка",
        category: "Credit / DSK",
        bgn: fromEur(123.86),
        eur: 123.86,
        issuer: "Groupama, Жилище",
        note: "За ДСК",
        status: "paid",
    },
    {
        id: "doc-026",
        sourceRow: 26,
        title: "Данък придобиване 3.09%",
        category: "Greek closing",
        bgn: fromEur(2781),
        eur: 2781,
        issuer: "ААДЕ",
        note: "3.09% от цената на Unit 19",
        status: "paid",
    },
    {
        id: "doc-027",
        sourceRow: 27,
        title: "Нотариални такси и първоначално вписване в имотен регистър",
        category: "Greek closing",
        bgn: fromEur(1140),
        eur: 1140,
        issuer: "Нотариус, ААДЕ",
        note: "Unit 19, платени на Радостина Грампас",
        status: "paid",
    },
    {
        id: "doc-032",
        sourceRow: 32,
        title: "Brokers fee for Unit 19, VAT excl.",
        category: "Greek closing",
        bgn: fromEur(1800),
        eur: 1800,
        issuer: "Progreso Real Estate, Василена",
        note: "2% от 90000, без ДДС",
        status: "paid",
    },
    {
        id: "doc-033",
        sourceRow: 33,
        title: "Първоначално вписване в кадастър",
        category: "Greek closing",
        bgn: fromEur(450),
        eur: 450,
        issuer: "ААДЕ",
        note: "0.5% от цената на Unit 19",
        status: "paid",
    },
    {
        id: "doc-034",
        sourceRow: 34,
        title: "Такси",
        category: "Greek closing",
        bgn: fromEur(130),
        eur: 130,
        issuer: "Нотариуса/Адвоката",
        note: "Да се види за какво точно се водят и как тия такси.",
        status: "clarify",
    },
    {
        id: "doc-035",
        sourceRow: 35,
        title: "Такси",
        category: "Greek closing",
        bgn: fromEur(680),
        eur: 680,
        issuer: "Нотариуса/Адвоката",
        note: "Да се види за какво точно се водят и как тия такси.",
        status: "clarify",
    },
    {
        id: "doc-036",
        sourceRow: 36,
        title: "Държавна такса E9",
        category: "Greek closing",
        bgn: fromEur(254),
        eur: 254,
        issuer: "ААДЕ",
        note: "Според АИ това е много по-малко, да се провери",
        status: "clarify",
    },
    {
        id: "doc-042",
        sourceRow: 42,
        title: "Регистрация договор за наем",
        category: "Post-acquisition",
        bgn: fromEur(350),
        eur: 350,
        issuer: "ААДЕ",
        note: "Платени на Радостина Грампас, това според АИ е безплатно, да се провери",
        status: "clarify",
    },
    {
        id: "doc-043",
        sourceRow: 43,
        title: "Решетки Unit 19 Северен прозорец",
        category: "Post-acquisition",
        bgn: fromEur(280),
        eur: 280,
        issuer: "B-Safe, Isaac Kandos",
        note: "Капаро, 50% от 560",
        status: "paid",
    },
    {
        id: "doc-031",
        sourceRow: 31,
        title: "Tires Zafira",
        category: "Vehicle / excluded",
        bgn: fromEur(150),
        eur: 150,
        issuer: "Примекс",
        note: "Гуми за Зафирата, всесезонни.",
        status: "excluded",
    },
    {
        id: "doc-037",
        sourceRow: 37,
        title: "Zafira ремонт",
        category: "Vehicle / excluded",
        bgn: fromEur(794.25),
        eur: 794.25,
        issuer: "6+",
        note: "Смяна масло и всички филтри, промивка/смяна антифриз и водна помпа, смяна ремъци и ролки",
        status: "excluded",
    },
    {
        id: "doc-040",
        sourceRow: 40,
        title: "Zafira софтуер",
        category: "Vehicle / excluded",
        bgn: fromEur(160),
        eur: 160,
        issuer: "Сервиз на бул. Европа",
        note: "Изчистване грешки, байпас на моторче вихрови клапи и ЕГР",
        status: "excluded",
    },
];
